"""Read/write dlms.toml.

We use stdlib `tomllib` for reads (Python 3.11+). Writes go through a small
hand-rolled emitter so we don't take a dependency on tomli-w just to render
a flat default file. Users are free to hand-edit the resulting file.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class WorkspaceCfg:
    name: str = "myproject"
    roots: list[str] = field(default_factory=lambda: ["."])
    shared: bool = True


@dataclass
class ScanCfg:
    include: list[str] = field(default_factory=list)
    exclude: list[str] = field(
        default_factory=lambda: [
            "node_modules", "dist", "build", ".venv", "target", ".dart_tool",
        ]
    )
    max_file_kb: int = 512
    follow_symlinks: bool = False


@dataclass
class IngestersCfg:
    enabled: list[str] = field(
        default_factory=lambda: ["readme", "manifest", "schema", "git", "symbols"]
    )


@dataclass
class BootstrapCfg:
    budget_seconds: int = 60
    token_ceiling: int = 4000


@dataclass
class RetrievalCfg:
    turn_token_cap: int = 3000
    embedder: str = "bge-small-en-v1.5"
    reranker: str = "ms-marco-MiniLM-L6"


@dataclass
class SyncCfg:
    mode: str = "git-jsonl"
    export_path: str = ".dlms/atoms.jsonl"


@dataclass
class HandoffCfg:
    capacity_warn_pct: int = 80
    capacity_halt_pct: int = 85
    keep_handoffs_days: int = 30


@dataclass
class BranchesCfg:
    protected: list[str] = field(default_factory=lambda: ["main", "stable"])


@dataclass
class Config:
    workspace: WorkspaceCfg = field(default_factory=WorkspaceCfg)
    scan: ScanCfg = field(default_factory=ScanCfg)
    ingesters: IngestersCfg = field(default_factory=IngestersCfg)
    bootstrap: BootstrapCfg = field(default_factory=BootstrapCfg)
    retrieval: RetrievalCfg = field(default_factory=RetrievalCfg)
    sync: SyncCfg = field(default_factory=SyncCfg)
    handoff: HandoffCfg = field(default_factory=HandoffCfg)
    branches: BranchesCfg = field(default_factory=BranchesCfg)


def load(path: Path) -> Config:
    """Load dlms.toml from `path`. Missing keys fall back to dataclass defaults."""
    raw: dict = {}
    if path.exists():
        with path.open("rb") as fh:
            raw = tomllib.load(fh)
    cfg = Config()
    if (ws := raw.get("workspace")):
        cfg.workspace = WorkspaceCfg(
            name=ws.get("name", cfg.workspace.name),
            roots=ws.get("roots", cfg.workspace.roots),
            shared=ws.get("shared", cfg.workspace.shared),
        )
    if (sc := raw.get("scan")):
        cfg.scan = ScanCfg(
            include=sc.get("include", cfg.scan.include),
            exclude=sc.get("exclude", cfg.scan.exclude),
            max_file_kb=sc.get("max_file_kb", cfg.scan.max_file_kb),
            follow_symlinks=sc.get("follow_symlinks", cfg.scan.follow_symlinks),
        )
    if (ig := raw.get("ingesters")):
        cfg.ingesters = IngestersCfg(enabled=ig.get("enabled", cfg.ingesters.enabled))
    if (bs := raw.get("bootstrap")):
        cfg.bootstrap = BootstrapCfg(
            budget_seconds=bs.get("budget_seconds", cfg.bootstrap.budget_seconds),
            token_ceiling=bs.get("token_ceiling", cfg.bootstrap.token_ceiling),
        )
    if (rt := raw.get("retrieval")):
        cfg.retrieval = RetrievalCfg(
            turn_token_cap=rt.get("turn_token_cap", cfg.retrieval.turn_token_cap),
            embedder=rt.get("embedder", cfg.retrieval.embedder),
            reranker=rt.get("reranker", cfg.retrieval.reranker),
        )
    if (sy := raw.get("sync")):
        cfg.sync = SyncCfg(
            mode=sy.get("mode", cfg.sync.mode),
            export_path=sy.get("export_path", cfg.sync.export_path),
        )
    if (ha := raw.get("handoff")):
        cfg.handoff = HandoffCfg(
            capacity_warn_pct=ha.get("capacity_warn_pct", cfg.handoff.capacity_warn_pct),
            capacity_halt_pct=ha.get("capacity_halt_pct", cfg.handoff.capacity_halt_pct),
            keep_handoffs_days=ha.get("keep_handoffs_days", cfg.handoff.keep_handoffs_days),
        )
    if (br := raw.get("branches")):
        cfg.branches = BranchesCfg(
            protected=br.get("protected", cfg.branches.protected),
        )
    return cfg


def render_default(name: str, roots: list[str]) -> str:
    """Render a starter dlms.toml. Mirrors dlms.toml.example, parameterized."""
    roots_toml = ", ".join(f'"{r}"' for r in roots)
    return f"""# dlms.toml — Living Memory Substrate config (auto-generated by `dlms init`)
# Hand-edit freely. Schema lives in dlms/SPEC.md.

[workspace]
name = "{name}"
roots = [{roots_toml}]
shared = true

[scan]
include = []
exclude = ["node_modules", "dist", "build", ".venv", "target", ".dart_tool"]
max_file_kb = 512
follow_symlinks = false

[ingesters]
enabled = ["readme", "manifest", "schema", "git", "symbols"]

[bootstrap]
budget_seconds = 60
token_ceiling = 4000

[retrieval]
turn_token_cap = 3000
embedder = "bge-small-en-v1.5"
reranker = "ms-marco-MiniLM-L6"

[sync]
mode = "git-jsonl"
export_path = ".dlms/atoms.jsonl"

[handoff]
capacity_warn_pct = 80
capacity_halt_pct = 85
keep_handoffs_days = 30

[branches]
protected = ["main", "stable"]
"""
